# Generated by Django 5.0.1 on 2024-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
