# Generated by Django 5.0.1 on 2024-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_joke_shared_jokes_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shared_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_newsfeed', to='jokes.shared_name'),
        ),
    ]
