# Generated by Django 5.0.1 on 2024-03-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_comment_commentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
    ]
