# Generated by Django 5.0.1 on 2024-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_shared_name_joke_shared_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='shared_users',
        ),
        migrations.AddField(
            model_name='joke',
            name='shared_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Shared_name',
        ),
    ]
